### ISSUE TITLE
encrypt() with output parameter can result in MemoryError

### ISSUE THREAD

**Issue by alexvh** [isislovecruft/python-gnupg#135]
Using encrypt() with an output parameter in place of encrypt_file() now requires the entire encrypted file to be read into memory which is infeasible for files larger than available RAM resulting in a MemoryError.

Traceback:
Exception in thread Thread-43:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 668, in _read_data
    result.data = type(data)().join(chunks)
MemoryError

**Comment by robertchen** [comment]
Anyone resolved  this issue?

**Comment by isislovecruft** [comment]
@alexvh The `_read_data()` function reads data from the result in 1KB increments in order to produce the result as a string, which is what you're asking for by calling `encrypt()`, and which is why `encrypt_file()` exists. Sorry, but if you ask Python to store a string that's larger than the available memory on your system, and my library gives you that string as requested, it's not my library's problem if you run out of memory.

**Comment by alexvh** [comment]
encrypt_file() doesn't exist courtesy of 295d98f and I'd argue that any function named encrypt() that can accept a file or byte stream as input and output to a file should not be bounded by memory constraints, but thanks for the attitude on the simple bug report, much appreciated.

**Comment by ndanl** [comment]
sorry for bringing this thread to life, @alexvh how did you solved this issue? or can some one point an example for solving this?
thanks,
Dan

**Comment by alexvh** [comment]
Switched to the original project (https://bitbucket.org/vinay.sajip/python-gnupg). It's actively maintained again and no longer suffers from the shell injection vulnerability. I actually only used this one by accident (I did "pip install gnupg" instead of "pip install python-gnupg").
